# Generated by Django 2.2.4 on 2019-10-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_item_item_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
