# Generated by Django 2.2.4 on 2019-10-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='AppleCartadmin',
        ),
    ]
