# Generated by Django 2.2.4 on 2019-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20191015_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=60)),
                ('user_number', models.IntegerField()),
                ('area', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('landmark', models.CharField(max_length=60)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('item_name', models.CharField(max_length=60)),
                ('item_price', models.IntegerField()),
                ('item_desc', models.CharField(max_length=60)),
                ('order_date', models.CharField(max_length=60)),
            ],
        ),
    ]
