# Generated by Django 2.2.4 on 2019-10-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_number',
            field=models.CharField(max_length=60),
        ),
    ]
