# Generated by Django 2.2.4 on 2019-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20191020_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
