# Generated by Django 2.2.4 on 2019-10-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_order_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='landmark',
            new_name='Landmark',
        ),
    ]
