# Generated by Django 2.2.4 on 2019-10-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20191020_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='no image found', upload_to='media/images/client/'),
        ),
    ]
