# Generated by Django 2.2.4 on 2019-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_catagory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='', upload_to='images/client/'),
        ),
    ]
