# Generated by Django 2.2.4 on 2019-11-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20191110_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
    ]
